services:
  authservice:
    container_name: "authservice"
    env_file:
      - .env
    build:
      context: .
    ports:
      - "${APP_PORT}:${SERVER_CONTAINER_PORT}"
    volumes:
      - .:/app
      - nodemodulesauthservice:/app/node_modules
    links:
      - db
    depends_on:
      - db
  db:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    env_file: .env
    ports:
      - "${LOCAL_DB_PORT}:${DB_CONTAINER_PORT}"
    volumes:
      - dbdata:/data/db
volumes:
  nodemodulesauthservice: {}
  dbdata: {}